spring:

  cloud:
    openfeign:
      client:
        config:
          telegram:
            url: ${TELEGRAM_API_URL}/bot${DEV_TELEGRAM_BOT_TOKEN}
            connect-timeout: 500
            read-timeout: 500

  messages:
    cache-duration: 0s

  datasource:
    url: ${DB_TEST_URL}
    username: ${DB_TEST_USERNAME}
    password: ${DB_TEST_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

telegram:
  bot:
    webhook:
      url: ${DEV_TELEGRAM_WEBHOOK_URL}
