spring:
  datasource:
    url: ${DB_TEST_URL}
    username: ${DB_TEST_USERNAME}
    password: ${DB_TEST_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
