spring:

  application:
    name: deplifybot

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: false
      okhttp:
        enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

telegram:
  bot:
    connections:
      value: 40
    webhook:
      path: /telegram/webhook
    token:
      bytes-size: 32

server:
  port: ${PORT:8080}
