spring:

  cloud:
    openfeign:
      client:
        config:
          telegram:
            url: ${TELEGRAM_API_URL}/bot${TELEGRAM_BOT_TOKEN}
            connect-timeout: 10000
            read-timeout: 15000

  messages:
    cache-duration: 15s

  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 50
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true

telegram:
  bot:
    init:
      enabled: true
    settings:
      webhook-url: ${TELEGRAM_WEBHOOK_URL}
      drop-pending-updates: false
