spring:

  application:
    name: deplifybot

  messages:
    basename: i18n/messages, i18n/ValidationMessages
    encoding: UTF-8
    fallback-to-system-locale: false

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: false
      okhttp:
        enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

telegram:
  bot:
    settings:
      webhook-path: ${TELEGRAM_WEBHOOK_PATH}
      allowed-http-connections: 40
      allowed-update-types:
        - message
        - callback_query
        - my_chat_member
      set-user-command-menu: all_private_chats
      secret-token-bytes-size: 32
      language-specs:
        - locale-tag: "und"
          language-code: null
          country-code: "DEFAULT"
        - locale-tag: "en"
          language-code: "en"
          country-code: "EN"
        - locale-tag: "ru"
          language-code: "ru"
          country-code: "RU"

server:
  port: ${PORT:8080}
